#' Dummy Trial Data with Permute-Block Randomization
#'
#' This dataset contains the dummy trial data with permute block randomization.
#'
#' @format A data frame with 400 rows and 3 columns:
#'   \describe{
#'     \item{id}{The ID of the patients.}
#'     \item{treatment}{The treatment assignment.}
#'     \item{s1}{The first stratification variable.}
#'     \item{s2}{The second stratification variable.}
#'     \item{covar}{The covariate.}
#'     \item{y}{The continuous response.}
#'     \item{y_b}{The binary response.}
#'   }
#'
#' @source The data is generated by the create_dummy.R script.
#'
#' @keywords dataset
"perm_block"
